train:
    dreambooth:
        _target_: src.datasets.dreambooth.DreamBoothTrainDataset
        data_path: C:\Users\raven\genai_projects_2025-main\data
        placeholder_token: sks
        class_name: budgie
        instance_transforms: ${transforms.instance_transforms.train}

val:
    db_liv_small:
      _target_: src.datasets.dreambooth.DreamBoothLivingSmall
      data_path: C:\Users\raven\genai_projects_2025-main\data
      placeholder_token: sks
      class_name: budgie
